name: "Docker Build"
description: "re"
inputs: 
  docker_file_path:
    required: true
    type: string
  service_name:
    required: true
    type: string
  build_args:
    required: false
    type: string
    default: ''
  ECR_REPOSITORY:
    description: 'AWS region'
    required: true
  container_name:
    required: true


runs: 
  using: "composite"

  steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ inputs.service_name }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ inputs.service_name }}-

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
      with:
        # role-to-assume: ${{secrets.ROLE_TO_ASSUME}}
        # aws-region: ${{secrets.REGION}}
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY }}
        aws-region: ${{ secrets.REGION }}

    - name: Login to Amazon ECR Public
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public
    
    - name: Set outputs
      id: vars
      shell: bash
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build and push
      id: build-and-push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        build-args: ${{ inputs.build_args }}
        file: ${{ inputs.docker_file_path }}
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ECR_REPOSITORY }}:${{ steps.vars.outputs.sha_short }}
    
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Pull the images 
      shell: bash
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_URL }} << 'EOF'
          aws ecr-public get-login-password --region ${{secrets.REGION}} | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}

          cd ~/pinterest/pinterest

          docker pull ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ECR_REPOSITORY }}:${{ steps.vars.outputs.sha_short }}

          TAG=${{ steps.vars.outputs.sha_short }}

          PREVIOUS_CONTAINER=$(docker ps -aqf "name=${{inputs.container_name}}")
          PREVIOUS_IMAGE=$(docker images -q --filter "reference=${{ steps.login-ecr.outputs.registry }}/${{ inputs.ECR_REPOSITORY }}")
          docker container rm -f $PREVIOUS_CONTAINER || true

          echo $PREVIOUS_IMAGE
          docker rmi -f $PREVIOUS_IMAGE || true

          FRONTEND_TAG=$TAG BACKEND_TAG=$TAG docker compose -f ec2-compose.yaml up -d --force-recreate ${{inputs.service_name}} 

        EOF
